export const ASSETS_ACTIONS = {
	GET_ASSETS_START: "GET_ASSETS_START",
	GET_ASSETS_SUCCESS: "GET_ASSETS_SUCCESS",
	GET_ASSETS_FAIL: "GET_ASSETS_FAIL",
	UPDATE_ASSET_INFO: "UPDATE_ASSET_INFO",
	CLEAR_ASSETS: "CLEAR_ASSETS",
};
